queries:
  dynamic_create_query: |
    SELECT 'CREATE TABLE IF NOT EXISTS ' || relname || E'\n(\n' ||
    array_to_string(
    array_agg(
    '    ' || column_name || ' ' ||  type ||
    CASE WHEN not is_nullable THEN ' NOT NULL' ELSE '' END
    )
    , E',\n'
    ) || E'\n);'
    FROM (
    SELECT
    c.relname,
    a.attname AS column_name,
    pg_catalog.format_type(a.atttypid, a.atttypmod) AS type,
    a.attnotnull AS is_nullable
    FROM pg_class c
    JOIN pg_attribute a ON a.attrelid = c.oid
    WHERE c.relname = '%s'
    AND a.attnum > 0
    AND NOT a.attisdropped
    ) AS tabledef
    GROUP BY relname;
