services:
  postgres-db:
    image: postgres:latest
    container_name: go-pg # Give the container a name
    environment:
      POSTGRES_USER: golang # Set the PostgreSQL username
      POSTGRES_PASSWORD: golang # Set the PostgreSQL password
      POSTGRES_DB: source  # Set the default database name
    expose: 
      - "5454"
    ports:
      - "5454:5454"  # Map the container's port 5432 to the host's port 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist data using a volume
    restart: always # Ensure the container restarts automatically
    command: -p 5454
  oracle-db:
    container_name: go-oracle # Give the container a name
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=golang
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  oracle-data:
  oracle-backup:  
  postgres-data:
